Fix webAudioDispatch/WebAudioDispatch capitalization discrepancy in requires
`devbuild` in gulp would halt on the following error. Not entirely sure
yet about its prior effects.

```
Error: Cannot find module '../core/webAudioDispatch' from '/home/sneakertack-sonoport/work/snp/soundmodels/src/lib/models'
```